Support additional command line options
bitnami/bitnami-docker-logstash pull request #5
Opened 2021-04-19 12:31 UTC by fengxsong

Support passing additional command line flags with `LOGSTASH_EXTA_ARGS` environment variable.

Ref: #4

2021-04-20 12:55 UTC, alemorcuq requested changes
Thanks for the PR, @fengxsong! Let's change the implementation a bit to make it similar to what we have in Keycloak: https://github.com/bitnami/bitnami-docker-keycloak

2021-04-20 12:55 UTC, alemorcuq commented on 7/debian-10/rootfs/opt/bitnami/scripts/logstash/run.sh
> +fi
Let's put this block below the line about exposing the API, so that the extra args are the last to be added.

Also, I will suggest this change to make it similar to Keycloak:

```suggestion
if [[ -n "$LOGSTASH_EXTRA_ARGS" ]]; then
    read -r -a extra_args <<<"$LOGSTASH_EXTRA_ARGS"
    args+=("${extra_args[@]}")
fi
```

2021-04-20 12:55 UTC, alemorcuq commented on README.md
> +Using the `LOGSTASH_EXTRA_ARGS` environment variable if you want to specify some more command line options such as `pipeline.workers` and `pipeline.batch.size`.
```suggestion
In case you want to add extra flags to the Logstash command, use the LOGSTASH_EXTRA_ARGS variable. Example:
```

2021-04-20 12:55 UTC, alemorcuq commented on README.md
> +$ docker run -d --env LOGSTASH_EXTRA_ARGS=" -w 4 -b 4096" bitnami/logstash:latest
```suggestion
docker run --name logstash \
  --env LOGSTASH_EXTRA_ARGS="-w 4 -b 4096" \
  bitnami/logstash:latest
```

2021-04-21 01:36 UTC, fengxsong commented on 7/debian-10/rootfs/opt/bitnami/scripts/logstash/run.sh
> +fi
Good poinit. I'll make this change.

2021-04-21 01:55 UTC, fengxsong commented on README.md
> +$ docker run -d --env LOGSTASH_EXTRA_ARGS=" -w 4 -b 4096" bitnami/logstash:latest
I think the format here should be consistent with the above.

2021-04-27 09:48 UTC, alemorcuq requested changes

2021-04-27 09:48 UTC, alemorcuq commented on README.md
> +$ docker run -d --env LOGSTASH_EXTRA_ARGS=" -w 4 -b 4096" bitnami/logstash:latest
You are completely right, @fengxsong. Let's remove this little space and we are done:

```suggestion
$ docker run -d --env LOGSTASH_EXTRA_ARGS="-w 4 -b 4096" bitnami/logstash:latest
```

2021-04-29 07:25 UTC, alemorcuq approved these changes
Thanks!

2021-04-29 07:33 UTC, merged

2021-04-29 07:33 UTC, alemorcuq commented
Thanks for the PR, @fengxsong ! A new version should be released soon with support for this feature.